---
title: "Diet diversity analysis"
output: html_document
date: "2024-07-26"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Reading in libs
```{r}
library(dplyr)
library(ggplot2)
library(phyloseq)
library(vegan)
library(forcats)
library(spaa)
library(tidyverse)
library(here)
library(iNEXT)
#library(hilldiv) # for calculating hill numbers! 
library(ggtext)
library(ggh4x)

```


```{r}

physeq_rra <- readRDS("banff_diet_phyloseq_cleaned_June162026.rds")
sample_data(physeq_rra)$Season = factor(sample_data(physeq_rra)$Season, 
                                         levels = c("Spring", "Summer", "Winter", "Fall"), 
                                         labels = c("Spring", "Summer", "Winter", "Winter"))


table(sample_data(physeq_rra)$Season, sample_data(physeq_rra)$Species)


```


## Individual mean sample richness and diversity 
```{r}

otu_matrix <- as.data.frame(otu_table(physeq_rra))
sample_metadata <- sample_data(physeq_rra)


# Calculate Hill numbers for each sample RICHNESS AND DIVERSITY 
hill_rich <- vegan::renyi(t(otu_matrix), scales = 0, hill = T)
hill_div <- vegan::renyi(t(otu_matrix), scales = 1, hill = T)

# Combine results with sample metadata
hill_rich <- tibble::rownames_to_column(as.data.frame(hill_rich), var = "SampleID") %>% 
  mutate(metric = "q0") %>% dplyr::select(SampleID, metric, value = "hill_rich")
hill_div <- tibble::rownames_to_column(as.data.frame(hill_div), var = "SampleID")%>% 
  mutate(metric = "q1") %>% dplyr::select(SampleID, metric, value = "hill_div")

hill <- rbind(hill_rich, hill_div)

hill2 <- left_join(hill, sample_metadata,  by = "SampleID") 
hill2_2 <- hill2 %>% filter(Species  %in% c("Elk", "Bison", "BighornSheep"))
hill2$Season = "All seasons"
hill2 <- rbind(hill2, hill2_2)
hill2$Species =factor(hill2$Species, levels = c("Bison",  
                                                   "BighornSheep",    "Elk",  "Goat",  "Deer",  "Moose"),
                            labels = c("Bison",  "Bighorn Sheep", "Elk", "Mountain Goat", "Deer spp.",  "Moose"))
hill2$Season = factor(hill2$Season, levels = c("All seasons",  "Winter", "Spring", "Summer"))






div_metrics <- left_join(hill, sample_metadata,  by = "SampleID") %>% 
  group_by(Species, metric) %>% 
  summarise(mean = mean(value), 
           sd = sd(value), 
           n = n()) %>% 
  mutate(ci = 1.95*sd/sqrt(n), 
         se = sd/sqrt(n)) %>%
  mutate(Season = "All seasons")%>% 
  mutate(upper_ci = mean + ci, 
         lower_ci = mean - ci)

div_metrics2 <- left_join(hill, sample_metadata,  by = "SampleID") %>% 
  filter(Season != "Fall") %>% 
  filter(Species %in% c("Elk", "Bison", "BighornSheep")) %>% 
  mutate(group = paste(Species, Season)) %>% 
  group_by(Species, Season, metric) %>% 
  summarise(mean = mean(value), 
           sd = sd(value), 
           n = n()) %>% 
  mutate(ci = 1.95*sd/sqrt(n), 
         se = sd/sqrt(n)) %>% 
  mutate(upper_ci = mean + ci, 
         lower_ci = mean - ci)
div_metrics <- rbind(div_metrics, div_metrics2)

div_metrics$Species =factor(div_metrics$Species, levels = c("Bison",  
                                                   "BighornSheep",    "Elk",  "Goat",  "Deer",  "Moose"),
                            labels = c("Bison",  "Bighorn Sheep", "Elk", "Mountain Goat", "Deer spp.",  "Moose"))
div_metrics$Season = factor(div_metrics$Season, levels = c("All seasons",  "Winter", "Spring", "Summer"))

div_metrics$metriclab = factor(div_metrics$metric, labels = c("Sample-level dietary richness ", "Sample-level dietary diversity"))


### metrics separately 
ggplot() + 
  geom_point(data = hill2[hill2$metric == "q0",], aes(x = Season, y =value, color = Species, shape = Species), alpha = 0.5,size = 0.5, 
             position = position_dodge(width = 0.8, preserve = "single")) + 
  geom_point(data = div_metrics[div_metrics$metric == "q0",], size = 3,
             aes(x = Season, y = mean, color = Species,  shape = Species), position = position_dodge(width = 0.8, preserve = "single"),  alpha = 1) + 
  
  geom_errorbar(data = div_metrics[div_metrics$metric == "q0",],
                aes(ymin = mean - ci, ymax = mean + ci, x = Season, y = mean, color = Species), position = position_dodge(width = 0.8,  preserve = "single"), width = 0.8, size = 1) +
  facet_wrap(.~metriclab, nrow = 2, scales = "free_y") + 
  theme_bw() + 
  labs( y =  expression("Richness of all taxa" ~ italic(q^0))) + xlab(NULL) + 
  scale_color_manual(values = c("#586028","tan1",  "#00A1B7",  "grey30",  "grey50",  "grey80")) +
    scale_shape_manual(values = c(16, 15,  17, 16, 16, 16)) + 
    theme(
      legend.background = element_blank(), legend.box.background = element_blank(),
    legend.position = c(0.6, 0.88), 
    legend.title = element_blank(),
    axis.text.x = element_text(size = 12, color = "black"), axis.title.y = element_text(size = 12, color = "black"), 
    axis.text.y = element_text(size = 10, color = "black"),  strip.text = element_text(size = 14)# increase facet label size

  ) + 
  scale_y_continuous(expand = expansion(mult = c(0, 0.01)), position = "right", limits = c(0, 125)) + 
  guides(color = guide_legend(ncol = 2), 
         shape = guide_legend(ncol= 2))

ggsave("Outputs/richness_mean_July2026.jpeg", width = 4, height = 4)

ggplot() + 
  geom_point(data = hill2[hill2$metric == "q1",], aes(x = Season, y =value, color = Species, shape = Species), alpha = 0.5,size = 0.5, 
             position = position_dodge(width = 0.8, preserve = "single")) + 
  geom_point(data = div_metrics[div_metrics$metric == "q1",], size = 3,
             aes(x = Season, y = mean, color = Species,  shape = Species), position = position_dodge(width = 0.8, preserve = "single"),  alpha = 1) + 
  
  geom_errorbar(data = div_metrics[div_metrics$metric == "q1",],
                aes(ymin = mean - ci, ymax = mean + ci, x = Season, y = mean, color = Species), position = position_dodge(width = 0.8,  preserve = "single"), width = 0.8, size = 1) +
  facet_wrap(.~metriclab, nrow = 2, scales = "free_y") + 
  theme_bw() + 
  labs( y =  expression("Diversity of typical taxa" ~ italic(q^1))) + xlab(NULL) + 
  scale_color_manual(values = c("#586028","tan1",  "#00A1B7",  "grey30",  "grey50",  "grey80")) +
    theme(
    legend.position = "none", 
    axis.text.x = element_text(size = 12, color = "black"), axis.title.y = element_text(size = 12, color = "black"), 
    axis.text.y = element_text(size = 10, color = "black"),  strip.text = element_text(size = 14)# increase facet label size

  ) + 
      scale_shape_manual(values = c(16, 15,  17, 16, 16, 16)) + 
  scale_y_continuous(expand = expansion(mult = c(0, 0.01)), position = "right", limits = c(0, 25)) 

ggsave("Outputs/diversity_mean_July2026.jpeg", width = 4, height = 4)
```

What about population-level richness and diversity (combining across samples in a season/species)
```{r}
# For incidence data (presence/absence per diet sample)
# needs number of species PER scat sample 
threshold0.pa <- decostand(t(otu_table(physeq_rra)), method="pa", MARGIN=1, zap = F) # by rows (samples)
#threshold0.pa <-t(otu_table(physeq_rra)) # by rows (samples)

### make a list, where each item of the list is our incidence data to put into iNEXT function to calculate 
### ALL SPECIES 
all_dat <- list(bis_all <- subset_samples(physeq_rra, Species == "Bison"), 
                bhs_all <- subset_samples(physeq_rra, Species == "BighornSheep"), 
                elk_all <- subset_samples(physeq_rra, Species == "Elk"), 
                deer_all <- subset_samples(physeq_rra, Species == "Deer")#, 
            #    moose_all <- subset_samples(physeq_rra, Species == "Moose"), 
                #goat_all <- subset_samples(physeq_rra, Species == "Goat")
)


names(all_dat) <- c("bis_all", "bhs_all", "elk_all", "deer_all")#, "moose_all", "goat_all")

### WINTER 
w_dat <- list(bis_w <- subset_samples(physeq_rra, Species == "Bison" & Season == "Winter"), 
                bhs_w <- subset_samples(physeq_rra, Species == "BighornSheep"  & Season == "Winter"), 
                elk_w <- subset_samples(physeq_rra, Species == "Elk" & Season == "Winter"))
names(w_dat) <- c("bis_w", "bhs_w", "elk_w")

### SPRING 
sp_dat <- list(bis_sp <- subset_samples(physeq_rra, Species == "Bison" & Season == "Spring"), 
                bhs_sp <- subset_samples(physeq_rra, Species == "BighornSheep"  & Season == "Spring"), 
                elk_sp <- subset_samples(physeq_rra, Species == "Elk" & Season == "Spring"))
names(sp_dat) <- c( "bis_sp", "bhs_sp", "elk_sp")

### SUMMER 
su_dat <- list( bis_su <- subset_samples(physeq_rra, Species == "Bison" & Season == "Summer"), 
                bhs_su <- subset_samples(physeq_rra, Species == "BighornSheep"  & Season == "Summer"), 
                elk_su <- subset_samples(physeq_rra, Species == "Elk" & Season == "Summer"))
names(su_dat) <- c("bis_su", "bhs_su", "elk_su")


get_incidence_data <- function(data){
  
  for(i in 1:length(data)){
  
  sample_data(data[[i]])$SampleID <- rownames(sample_data(data[[i]]))
  
  dat <- threshold0.pa[rownames(threshold0.pa) %in% sample_data(data[[i]])$SampleID,]
  dat <- colSums(dat)
  dat <- append(dat, nrow(sample_data(data[[i]])), after=0)
 data[[i]] <- dat

}

  return(data)
  
}


### getting incidence data 
all_dat <- get_incidence_data(all_dat)
w_dat <- get_incidence_data(w_dat)
sp_dat <- get_incidence_data(sp_dat)
su_dat <- get_incidence_data(su_dat)


############## asymptotic estimates of richness 
# Combine all compiled lists into one master list
master_inext_list <- c(all_dat, w_dat, sp_dat, su_dat)

# Check the names to ensure they look like: "bis_all", "bis_w", etc.
names(master_inext_list)

# Run iNEXT on the complete set
inext_output <- iNEXT(master_inext_list, q = 0, datatype = "incidence_freq", endpoint = 150)

asyptotic <-  inext_output$AsyEst %>% filter(Diversity == "Species richness") %>% 
  dplyr::select(Assemblage, Observed, Estimator, LCL, UCL)
write.csv(asyptotic, "Outputs/richness_asymptotic.csv")

ggplot(asyptotic[!grepl("all", asyptotic$Assemblage),], aes( x = Assemblage, y = Estimator)) + 
  geom_point() + geom_errorbar(aes(ymin = LCL, ymax =UCL))




# extract the raw interpolation/extrapolation data
curve_data <- inext_output$iNextEst$coverage_based

# 2. Clean up the labels and split "bis_w" into separate columns
curve_data_cleaned <- curve_data %>%
  # Split the dynamic text string at the underscore
  separate(Assemblage, into = c("Species_Code", "Season_Code"), sep = "_", remove = FALSE) %>%
  # Clean up factor levels so they display beautifully on your plot axes
  mutate(
    Species = case_when(
      Species_Code == "bis"  ~ "Bison",
      Species_Code == "bhs"  ~ "Bighorn sheep",
      Species_Code == "elk"  ~ "Elk",
      Species_Code == "deer" ~ "Deer spp.",
      TRUE ~ Species_Code
    ),
    Season = case_when(
      Season_Code == "all" ~ "All seasons",
      Season_Code == "w"   ~ "Winter",
      Season_Code == "sp"  ~ "Spring",
      Season_Code == "su"  ~ "Summer",
      TRUE ~ Season_Code
    ),
    # Make sure Season follows a clean ecological timeline
    Season = factor(Season, levels = c("All seasons", "Winter", "Spring", "Summer")),
    Species = factor(Species, levels = c("Bison", "Bighorn sheep", "Elk", "Deer spp."))
  ) %>% 
  filter(t < 150) %>% 
  filter(!(t > 50 & Season != "All seasons"))
# 3. Create the custom faceted plot using standard ggplot2
curve_data_cleaned$param <- "Population-level dietary richness"

custom_curve_plot <- ggplot(curve_data_cleaned, aes(x = t, y = qD, color = Species, fill = Species)) +
  # Solid lines for the interpolated data (collected field effort)
  geom_line(data = filter(curve_data_cleaned, Method == "Rarefaction"), aes(x = t, y = qD, color = Species),
            linewidth = 1) +
   geom_point(data = filter(curve_data_cleaned, Method == "Observed"), aes(x = t, y = qD, color = Species, shape = Species),
            size = 3) +
  # Dashed lines for the extrapolated data (mathematical prediction)
  geom_line(data = filter(curve_data_cleaned, Method == "Extrapolation"), aes(x = t, y = qD, color = Species),
            linewidth = 1, linetype = "dashed") +
  # Shaded 95% confidence intervals
  geom_ribbon(aes(ymin = qD.LCL, ymax = qD.UCL), alpha = 0.15, color = NA) +
  
  # FACET: Grid layout (Rows = Seasons, Columns = Species)
  facet_grid2(Season ~ param,scales = "free_x", independent = "x") + 
  
  # Styling overrides
  scale_color_manual(values = c("#586028", "tan1", "#00A1B7", "grey80")) +
  scale_fill_manual(values = c("#586028", "tan1", "#00A1B7", "grey80")) +
  scale_shape_manual(values = c(16, 15, 17, 16)) + 
  labs(
    x = "Number of samples", 
    y = expression("Cumulative richness " ~ italic(q^0)),
  ) +
  theme_bw() +
  theme(
    legend.position = "top", # Legend is redundant since facets are labeled!
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    strip.text = element_text(size = 13, face = "plain"),
    axis.text = element_text(size = 10, color = "black"),
    axis.title = element_text(size = 12, color = "black"),
          legend.background = element_blank(), legend.box.background = element_blank(),

    panel.grid.major = element_line(color = "grey95", linewidth = 0.3),
    panel.grid.minor = element_blank()
  )
custom_curve_plot


ggsave(plot = custom_curve_plot, filename = "Outputs/rarefaction_curves_July2026.jpeg", height = 8, width = 5, dpi = 300)
```




# INTRASPECIFIC VARIATION (dispersion)
trying to get dispersion (intraspecific differences!) based on some of Beth's YNP code - yes, it wokrs!
```{r}

### all seasons combined
all <-  subset_samples(physeq_rra, Species %in% c("BighornSheep", "Bison", "Elk", "Deer"))
bray_dist_core <- phyloseq::distance(all, method = "bray") ## calculating bray-curtis dissimilarity 
beta_all <- betadisper(bray_dist_core, group=sample_data(all)$Species,  # calculating intraspecific dissimilarity 
                        bias.adjust = TRUE, type = "centroid")
permutest(beta_all) # groups differ 
tukey_all <- TukeyHSD(beta_all)[["group"]] # using a tukey test to see which comparisons are significantly different 
## okay so bighorn sheep have highest intraspecific differentiation, then elk, then bison 
tukey_all <- as.data.frame(tukey_all) %>% mutate(Species = rownames(.), Season = "All Seasons")


### do this for each of our seasons separately ##############

# winter 
w <-  subset_samples(physeq_rra, Season == "Winter" & Species %in% c("BighornSheep", "Bison", "Elk"))
table(sample_data(w)$Species)
bray_dist_core <- phyloseq::distance(w, method = "bray") ## calculating bray-curtis dissimilarity 
beta_w <- betadisper(bray_dist_core, group=sample_data(w)$Species,  # calculating intraspecific dissimilarity 
                        bias.adjust = TRUE, type = "centroid")
permutest(beta_w) # groups differ 

tukey_w <- TukeyHSD(beta_w)[["group"]] # using a tukey test to see which comparisons are significantly different 
tukey_w <- as.data.frame(tukey_w) %>% mutate(Species = rownames(.), Season = "Winter")

## spring 
sp <-  subset_samples(physeq_rra, Season == "Spring" & Species %in% c("BighornSheep", "Bison", "Elk"))
bray_dist_core <- phyloseq::distance(sp, method = "bray") ## calculating bray-curtis dissimilarity 
beta_sp <- betadisper(bray_dist_core, group=sample_data(sp)$Species,  # calculating intraspecific dissimilarity 
                        bias.adjust = TRUE, type = "centroid")
permutest(beta_sp)
tukey_sp <- TukeyHSD(beta_sp)[["group"]] # using a tukey test to see which comparisons are significantly different 
tukey_sp <- as.data.frame(tukey_sp) %>% mutate(Species = rownames(.), Season = "Spring")

## summer
su <-  subset_samples(physeq_rra, Season == "Summer" & Species %in% c("BighornSheep", "Bison", "Elk"))
bray_dist_core <- phyloseq::distance(su, method = "bray") ## calculating bray-curtis dissimilarity 
beta_su <- betadisper(bray_dist_core, group=sample_data(su)$Species,  # calculating intrasuecific dissimilarity 
                        bias.adjust = TRUE, type = "centroid")
permutest(beta_su)
tukey_su <- TukeyHSD(beta_su)[["group"]] # using a tukey test to see which comparisons are significantly different 

tukey_su <- as.data.frame(tukey_su) %>% mutate(Species = rownames(.), Season = "Summer")


all_tukeys <- rbind(tukey_all, tukey_sp, tukey_su, tukey_w)
write.csv(all_tukeys, "Outputs/intraspecific_diet_dissimilarity_comparisons_tukey.csv")

## all intraspecific values 
betaw <- data.frame(beta_w$group.distances) %>% mutate(Season = "Winter") %>% rename(Dispersion = beta_w.group.distances)
betasp <- data.frame(beta_sp$group.distances) %>% mutate(Season = "Spring") %>% rename(Dispersion = beta_sp.group.distances)
betasu <- data.frame(beta_su$group.distances) %>% mutate(Season = "Summer") %>% rename(Dispersion = beta_su.group.distances)
betaall <- data.frame(beta_all$group.distances) %>% mutate(Season = "All") %>% rename(Dispersion = beta_all.group.distances)

betas <- rbind(betaw, betasp, betasu, betaall) %>% mutate(Species = rownames(.))


write.csv(betas, "Outputs/intraspecific_diet_dissimilarity.csv")


```

